project_id = "hbmebifvlghmhuthofnq"

[functions.receive-trade]
verify_jwt = false

[functions.validate-predictions]
verify_jwt = false

[functions.market-data]
verify_jwt = false

[functions.exchange-connect]
verify_jwt = false
